### PR TITLE
Printing also the type of labelled objects

### PR DESCRIPTION
**Pull request by larmarange**
Proposition to also display the type of a labelled object (as this information is "hidden" by the labelled class).

Example:
```
> s1 <- labelled(c("M", "M", "F"), c(Male = "M", Female = "F"))
> s1
<Labelled (character)>
[1] M M F

Labels:
 value  label
     M   Male
     F Female
> s2 <- labelled(c(1, 1, 2), c(Male = 1, Female = 2))
> s2
<Labelled (double)>
[1] 1 1 2

Labels:
 value  label
     1   Male
     2 Female
```

### CODE REVIEW

**Comment by larmarange** [comment]
In addition, would it be appropriate to also display the variable label?

I.e. something like:

```
<Labelled (character)> Sex of the respondant
[1] M M F

Labels:
 value  label
     M   Male
     F Female
```

**Comment by hadley** [comment]
I don't think the parens are necessary here. 

I'd rather not print the label, I think because it would be more inconsistent with print method for other columns. But I don't feel strongly about it.

**Comment by larmarange** [comment]
The pull request has been updated accordindly

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
