### PR TITLE
Date variables in SPSS should be imported as date, not datetime

### PR DESCRIPTION
**Pull request by larmarange**
NB: dates are stored in seconds in SPSS

### CODE REVIEW

**Comment by hadley** [comment]
I'd say that SPSS doesn't have a date data type, so I don't like this implementation because it confuses the type in SPSS with its representation in R.

**Comment by larmarange** [comment]
One of the main issue is that once imported, it's not possible to know what were the original formats in SPSS. Therefore it's not possible to create a function to reconvert from POSIXct to Date only the variables who had a Date format in SPSS (while keeping POSIXct for variables who had a DateTime format in SPSS).

I would argue that it could be therefore an optional argument for `read_spss` (for converting variables with a date format to Date instead of POSIXct, even if I understood that the underlying way to store this information is always datetime in SPSS) OR another option would be to attach an attribute (to the imported data.frame or to the variable) with the content of the original format in SPSS (allowing to write a custom post-import function).

**Comment by hadley** [comment]
I don't think it needs to be an option - I just think your current implantation is confusing. I think the idea is fine

**Comment by larmarange** [comment]
> I think the idea is fine

Sorry, I'm confused. Which idea are referring to?

**Comment by hadley** [comment]
The basic idea of the PR is fine (turn them into dates) is fine, but I don't like the implementation, because I think it's confusing.

**Comment by larmarange** [comment]
Alright. As you have a better knowledge of the code of the package, would you have a suggestion?

**Comment by hadley** [comment]
Hmmmm, I'm warming up to this approach :) It is simple and does the job.  

Would you mind also including a couple of unit tests? And a bullet point in NEWS.

**Comment by larmarange** [comment]
I have updated the pull request.

Regards

**Comment by larmarange** [comment]
Is there any additional issue remaining? Or could it be merges?

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
